import 'modules/admin-lte/plugins/jQueryUI/jquery-ui.min'
import 'modules/admin-lte/plugins/fastclick/fastclick'
import 'modules/admin-lte/plugins/slimScroll/jquery.slimscroll.min'
import 'modules/admin-lte/dist/js/app.min'

import '@fortawesome/fontawesome-free/css/all.min'
import 'modules/ionicons/dist/css/ionicons.min'
import 'modules/admin-lte/bootstrap/css/bootstrap.min'
import 'modules/admin-lte/dist/css/AdminLTE.min'
import 'modules/admin-lte/dist/css/skins/_all-skins.min'
import 'modules/admin-lte/plugins/iCheck/flat/blue'
import './custom'